{{- if .Values.snapshot.enabled -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.snapshot.snapshotController.name}}
  namespace: {{ .Release.Namespace }}
{{ include "azurefile.labels" . | indent 2 }}
spec:
  replicas: {{ .Values.snapshot.snapshotController.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.snapshot.snapshotController.name}}
  template:
    metadata:
{{ include "azurefile.labels" . | indent 6 }}
        app: {{ .Values.snapshot.snapshotController.name}}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.snapshotController }}
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
{{- with .Values.controller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.snapshot.snapshotController.name}}
{{- if eq .Values.snapshot.apiVersion "beta" }}
          image: "{{ .Values.snapshot.image.csiSnapshotController.repository }}:{{ .Values.snapshot.image.csiSnapshotController.tag }}"
{{- else }}
          image: "{{ .Values.snapshot.image.csiSnapshotController.repository }}:{{ .Values.snapshot.image.csiSnapshotController.gaTag }}"
{{- end }}
          args:
            - "--v=2"
            - "--leader-election=false"
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          imagePullPolicy: {{ .Values.snapshot.image.csiSnapshotController.pullPolicy }}
{{- end -}}
