---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: file.csi.azure.com
spec:
  attachRequired: {{ .Values.controller.attachRequired }}
  podInfoOnMount: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
