{{- if .Values.rbac.create -}}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-{{ .Values.rbac.name }}-node-secret-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-{{ .Values.rbac.name }}-node-secret-binding
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.node }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-{{ .Values.rbac.name }}-node-secret-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
