apiVersion: v1
entries:
  azurefile-csi-driver:
  - apiVersion: v1
    appVersion: v1.26.3
    created: "2023-05-19T06:53:46.395239346Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6aa07eea40b14d856b7d66979dbb67a6c4b0f4660a8a950d12372d261b1c016b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/latest/azurefile-csi-driver-v1.26.3.tgz
    version: v1.26.3
  - apiVersion: v1
    appVersion: v1.26.3
    created: "2023-05-19T06:53:46.420568109Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 61be13c10618eb0dac60bd27b26a037b5c251fffc945345d03b207a3e091ba76
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.3/azurefile-csi-driver-v1.26.3.tgz
    version: v1.26.3
  - apiVersion: v1
    appVersion: v1.26.2
    created: "2023-05-19T06:53:46.419540097Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d710b8282d9461946d596a8cbe6b91e57950eb6cf793bc180ad897ab5a07596b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.2/azurefile-csi-driver-v1.26.2.tgz
    version: v1.26.2
  - apiVersion: v1
    appVersion: v1.26.1
    created: "2023-05-19T06:53:46.417599549Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: b1c78e2c38869f9430f3e2e671fb168db803eab2fbc0ef905eacdf8794d7968a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.1/azurefile-csi-driver-v1.26.1.tgz
    version: v1.26.1
  - apiVersion: v1
    appVersion: v1.26.0
    created: "2023-05-19T06:53:46.416629548Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 98d15a8ced671a7c3d9aec8ebe00b58abeecb5f65ab966c9c01c4f39121adc0c
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.0/azurefile-csi-driver-v1.26.0.tgz
    version: v1.26.0
  - apiVersion: v1
    appVersion: v1.25.1
    created: "2023-05-19T06:53:46.415645108Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2bf374cc321c5bc8e76e06cd5df85ce7d7d14574397e7e7f7173077393f554c4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.25.1/azurefile-csi-driver-v1.25.1.tgz
    version: v1.25.1
  - apiVersion: v1
    appVersion: v1.25.0
    created: "2023-05-19T06:53:46.414669551Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: ba80dcd23dade4e62b39d3dc638c599e9d5e100009fa14d4164bfc8966fea3dd
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.25.0/azurefile-csi-driver-v1.25.0.tgz
    version: v1.25.0
  - apiVersion: v1
    appVersion: v1.24.0
    created: "2023-05-19T06:53:46.413629049Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 1905eb862745d4a7f57c5de96848cee194adf827086984b75bcaefce5c90142b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.0/azurefile-csi-driver-v1.24.0.tgz
    version: v1.24.0
  - apiVersion: v1
    appVersion: v1.23.0
    created: "2023-05-19T06:53:46.411940158Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5fcb33617d16e90df1e7041b0df02e5bd92595e86381db30d356b0b2e3500bc4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.23.0/azurefile-csi-driver-v1.23.0.tgz
    version: v1.23.0
  - apiVersion: v1
    appVersion: v1.22.0
    created: "2023-05-19T06:53:46.410687816Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 253d87a8b876dbdd55870a7fee88547393179d03f193661125f5a0b63411f922
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.22.0/azurefile-csi-driver-v1.22.0.tgz
    version: v1.22.0
  - apiVersion: v1
    appVersion: v1.21.0
    created: "2023-05-19T06:53:46.409694974Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d45bf3455ebadc9cc5afaf9da66aa1ea1d4b719cfdff5af661f93bb26c01a504
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.21.0/azurefile-csi-driver-v1.21.0.tgz
    version: v1.21.0
  - apiVersion: v1
    appVersion: v1.20.0
    created: "2023-05-19T06:53:46.40873767Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 7cc43d57a79137aea5414fb51a9bbd77bb679b29ee49c06865c1a5b9ba60be99
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.20.0/azurefile-csi-driver-v1.20.0.tgz
    version: v1.20.0
  - apiVersion: v1
    appVersion: v1.19.0
    created: "2023-05-19T06:53:46.40724813Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 18f6efbed424efd661fde43be2e5a48a5012a46a7938c33b36963cbd9875a5af
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.19.0/azurefile-csi-driver-v1.19.0.tgz
    version: v1.19.0
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2023-05-19T06:53:46.405507396Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 696ca23d9ee517f71ef5e852955c8d0f1017c331c025426c6fcbe7a06d006c66
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.18.0/azurefile-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2023-05-19T06:53:46.40460595Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5632f61265a3b78dce3e2b15e07cc9b14a7f54a778878c02ca2d9fe69ca0344e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.17.0/azurefile-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2023-05-19T06:53:46.403714431Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: a7a2d57e8eca7dc06c8b2cffb9bccb857753eb110b8e70760b3e04f4e6a87552
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.16.0/azurefile-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2023-05-19T06:53:46.402774795Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: c1a31dadce233a90c19dce70f6cc92ba2e20bbaa1b1883baea72381d09303118
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.15.0/azurefile-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2023-05-19T06:53:46.40181523Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 0c9ad4afa5ebfdb2851ad93eb16a0382d61448714b7556899360730a2fdf463a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.14.0/azurefile-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2023-05-19T06:53:46.400128271Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 214042b029d858b50a0f8bba33a7aa2b41d1b67bce16f957ca183ae7438dac3f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.13.0/azurefile-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2023-05-19T06:53:46.399140547Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fbd63929671066a26df898d32282a6e79c39499a39c71761c546d069459d847d
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.12.0/azurefile-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2023-05-19T06:53:46.3982205Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 76bd438f8391d08235b09fbca859f25a9fcf8e018fd1e7e33444ca9ea946ce4b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.11.0/azurefile-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2023-05-19T06:53:46.397267935Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 845a9de8b571b255d05ae9c643d9b90a57fe6507ff3fb735c88b41f99f6f28dc
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.10.0/azurefile-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: v1.9.0
    created: "2023-05-19T06:53:46.426709662Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 59a8057fbbd6d59919b84ef0c3396d5a0a46d1f29df604457db676f4af63c714
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.9.0/azurefile-csi-driver-v1.9.0.tgz
    version: v1.9.0
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2023-05-19T06:53:46.425741685Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 455b7c342194311046df526d10926d94f3bef24f753a07003fb1cad211c4cb52
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.8.0/azurefile-csi-driver-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.7.0
    created: "2023-05-19T06:53:46.424707155Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 057b3f6ef6001d3457fbffc27f90316c981a089696abd3d38bcc8de5537dfa6f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.7.0/azurefile-csi-driver-v1.7.0.tgz
    version: v1.7.0
  - apiVersion: v1
    appVersion: v1.6.0
    created: "2023-05-19T06:53:46.423156723Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: cc2a0dda824cdda4e8141e26878bbb481c5a52e45785a5dbf72e54f2a376e522
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.6.0/azurefile-csi-driver-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2023-05-19T06:53:46.422474584Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2258177477415ddecd83dc46dfd88833223623224c7fe396590b617082bcd845
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.5.0/azurefile-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2023-05-19T06:53:46.421775237Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 40e9bc4ee187789166fcb7c3c82b85b33ecd3a6096266fe74e411d6b48961ece
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.4.0/azurefile-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2023-05-19T06:53:46.421108348Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 12942f422b7cccbfe950bbdbd5c844f5ae4b7c292f32389cba312730a6fe9a62
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.3.0/azurefile-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2023-05-19T06:53:46.407762854Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: b62f44b757416a9e1f5a91e19285f5f5056ec6068802dd9cd82373bef40c9ee9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.2.0/azurefile-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2023-05-19T06:53:46.396348225Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 675d96b309a1c5c491053ebbb854c046737420929c4f0692839afdaaf0db3933
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.1.0/azurefile-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2023-05-19T06:53:46.395827717Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6fd5e54e949ef1061a08d5477bc580204c91dde8f01da195e95dd60ade209492
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.0.0/azurefile-csi-driver-v1.0.0.tgz
    version: v1.0.0
generated: "2023-05-19T06:53:46.392997476Z"
