apiVersion: v1
entries:
  azurefile-csi-driver:
  - apiVersion: v1
    appVersion: v1.29.10
    created: "2025-01-06T11:35:23.847337054Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fac12cd7a4b1142e50d83112bdf659e5f1dacb0862bebc3b7cd9c0e54ef0c386
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.10/azurefile-csi-driver-v1.29.10.tgz
    version: v1.29.10
  - apiVersion: v1
    appVersion: v1.29.10
    created: "2025-01-06T11:35:23.814425821Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fac12cd7a4b1142e50d83112bdf659e5f1dacb0862bebc3b7cd9c0e54ef0c386
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/latest/azurefile-csi-driver-v1.29.10.tgz
    version: v1.29.10
  - apiVersion: v1
    appVersion: v1.29.9
    created: "2025-01-06T11:35:23.857097869Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 9f4a8a480206da8c1bfb93ae19a070a2c7cf34098236f79ac29da5f33f0ca621
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.9/azurefile-csi-driver-v1.29.9.tgz
    version: v1.29.9
  - apiVersion: v1
    appVersion: v1.29.8
    created: "2025-01-06T11:35:23.85599079Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6b6edf2236207d589b90051f92bbe2a2ba5b770dfa2d1ec457dab7f12052ee76
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.8/azurefile-csi-driver-v1.29.8.tgz
    version: v1.29.8
  - apiVersion: v1
    appVersion: v1.29.7
    created: "2025-01-06T11:35:23.854900594Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d31aba313d13f53e90ad41ccbc65ff4d95c957dd22672d634a98c2a2998dc5e9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.7/azurefile-csi-driver-v1.29.7.tgz
    version: v1.29.7
  - apiVersion: v1
    appVersion: v1.29.6
    created: "2025-01-06T11:35:23.853769533Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 9d385d18e40c04306435e939ebd38939d15f0dc2e6837d1c675811fe0fae9eba
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.6/azurefile-csi-driver-v1.29.6.tgz
    version: v1.29.6
  - apiVersion: v1
    appVersion: v1.29.5
    created: "2025-01-06T11:35:23.851762438Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 99079a45e3826ff78a484d7f721ce84d7bb99663738f7a3b37a76e5df9aa0669
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.5/azurefile-csi-driver-v1.29.5.tgz
    version: v1.29.5
  - apiVersion: v1
    appVersion: v1.29.4
    created: "2025-01-06T11:35:23.850688137Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 820020b2a8c919c8dbd28b4a92767e2feeb4d282ac6003b5781fc6abcbc5e0c7
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.4/azurefile-csi-driver-v1.29.4.tgz
    version: v1.29.4
  - apiVersion: v1
    appVersion: v1.29.3
    created: "2025-01-06T11:35:23.849599465Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: e4a96134973d29277430319c38cb5163f93e20561b2541f4b2b51126ef6e20a8
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.3/azurefile-csi-driver-v1.29.3.tgz
    version: v1.29.3
  - apiVersion: v1
    appVersion: v1.29.2
    created: "2025-01-06T11:35:23.848497188Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 1d1a7075f40821228925e1bb2d7addc8418222c923ea9bac311d49510b262cb9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.2/azurefile-csi-driver-v1.29.2.tgz
    version: v1.29.2
  - apiVersion: v1
    appVersion: v1.29.1
    created: "2025-01-06T11:35:23.845181737Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: a7e3bc8bb3e17153f35387f2040210d72ac5545a9446b0a37660273b5635e11d
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.1/azurefile-csi-driver-v1.29.1.tgz
    version: v1.29.1
  - apiVersion: v1
    appVersion: v1.29.0
    created: "2025-01-06T11:35:23.844067939Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2da242b471ff0eaf6ea3f1a9d2c1f6aaa1b78c8cbb4e850bbefb336e043b8098
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.0/azurefile-csi-driver-v1.29.0.tgz
    version: v1.29.0
  - apiVersion: v1
    appVersion: v1.28.3
    created: "2025-01-06T11:35:23.842981073Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 58e138f7a8f2a925c56ca26dc220cab2dc723691c23fd011b457624d11889395
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.3/azurefile-csi-driver-v1.28.3.tgz
    version: v1.28.3
  - apiVersion: v1
    appVersion: v1.28.2
    created: "2025-01-06T11:35:23.841880439Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 426fad83a42035af15af775bd37c73309ef0cfe22686babb0668be71da70a66e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.2/azurefile-csi-driver-v1.28.2.tgz
    version: v1.28.2
  - apiVersion: v1
    appVersion: v1.27.3
    created: "2025-01-06T11:35:23.840765864Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 330d2b11f93e2b10d36f64ed6de528b61351ca794dd9b2c3690c6f6790008732
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.27.3/azurefile-csi-driver-v1.27.3.tgz
    version: v1.27.3
  - apiVersion: v1
    appVersion: v1.27.2
    created: "2025-01-06T11:35:23.839154783Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: ab72e0e5f360a38f63e87147ef47ef213016578e8ba64fbb32ecaf2aad7ffdf3
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.27.2/azurefile-csi-driver-v1.27.2.tgz
    version: v1.27.2
  - apiVersion: v1
    appVersion: v1.26.6
    created: "2025-01-06T11:35:23.837990303Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 3c20488343b47ed618e8c809f6fcdd83f22e00a4d07c78ca097573cafd7075a9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.6/azurefile-csi-driver-v1.26.6.tgz
    version: v1.26.6
  - apiVersion: v1
    appVersion: v1.26.5
    created: "2025-01-06T11:35:23.836969133Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 62ac6ab864264ee1e2fb86e8093c8e8263c2c0d3bafff60704c31fd72e40c604
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.5/azurefile-csi-driver-v1.26.5.tgz
    version: v1.26.5
  - apiVersion: v1
    appVersion: v1.25.1
    created: "2025-01-06T11:35:23.835953101Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2bf374cc321c5bc8e76e06cd5df85ce7d7d14574397e7e7f7173077393f554c4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.25.1/azurefile-csi-driver-v1.25.1.tgz
    version: v1.25.1
  - apiVersion: v1
    appVersion: v1.24.7
    created: "2025-01-06T11:35:23.834933189Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 9e5b3f32ad823f845e5a09af230f7a934851943d6afcab3bd545233838680d83
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.7/azurefile-csi-driver-v1.24.7.tgz
    version: v1.24.7
  - apiVersion: v1
    appVersion: v1.24.6
    created: "2025-01-06T11:35:23.833669186Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: dbd0a6e27a09fec002c57029bd6e34a6ee92d1c10e708935e3f2150069a35ee5
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.6/azurefile-csi-driver-v1.24.6.tgz
    version: v1.24.6
  - apiVersion: v1
    appVersion: v1.23.0
    created: "2025-01-06T11:35:23.831979205Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5fcb33617d16e90df1e7041b0df02e5bd92595e86381db30d356b0b2e3500bc4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.23.0/azurefile-csi-driver-v1.23.0.tgz
    version: v1.23.0
  - apiVersion: v1
    appVersion: v1.22.0
    created: "2025-01-06T11:35:23.83096075Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 253d87a8b876dbdd55870a7fee88547393179d03f193661125f5a0b63411f922
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.22.0/azurefile-csi-driver-v1.22.0.tgz
    version: v1.22.0
  - apiVersion: v1
    appVersion: v1.21.0
    created: "2025-01-06T11:35:23.82991387Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d45bf3455ebadc9cc5afaf9da66aa1ea1d4b719cfdff5af661f93bb26c01a504
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.21.0/azurefile-csi-driver-v1.21.0.tgz
    version: v1.21.0
  - apiVersion: v1
    appVersion: v1.20.0
    created: "2025-01-06T11:35:23.828856324Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 7cc43d57a79137aea5414fb51a9bbd77bb679b29ee49c06865c1a5b9ba60be99
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.20.0/azurefile-csi-driver-v1.20.0.tgz
    version: v1.20.0
  - apiVersion: v1
    appVersion: v1.19.0
    created: "2025-01-06T11:35:23.826579318Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 18f6efbed424efd661fde43be2e5a48a5012a46a7938c33b36963cbd9875a5af
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.19.0/azurefile-csi-driver-v1.19.0.tgz
    version: v1.19.0
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2025-01-06T11:35:23.825324691Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 696ca23d9ee517f71ef5e852955c8d0f1017c331c025426c6fcbe7a06d006c66
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.18.0/azurefile-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2025-01-06T11:35:23.82434981Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5632f61265a3b78dce3e2b15e07cc9b14a7f54a778878c02ca2d9fe69ca0344e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.17.0/azurefile-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2025-01-06T11:35:23.823418229Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: a7a2d57e8eca7dc06c8b2cffb9bccb857753eb110b8e70760b3e04f4e6a87552
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.16.0/azurefile-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2025-01-06T11:35:23.822481091Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: c1a31dadce233a90c19dce70f6cc92ba2e20bbaa1b1883baea72381d09303118
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.15.0/azurefile-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2025-01-06T11:35:23.821550383Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 0c9ad4afa5ebfdb2851ad93eb16a0382d61448714b7556899360730a2fdf463a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.14.0/azurefile-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2025-01-06T11:35:23.82052948Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 214042b029d858b50a0f8bba33a7aa2b41d1b67bce16f957ca183ae7438dac3f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.13.0/azurefile-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2025-01-06T11:35:23.818532243Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fbd63929671066a26df898d32282a6e79c39499a39c71761c546d069459d847d
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.12.0/azurefile-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2025-01-06T11:35:23.817462046Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 76bd438f8391d08235b09fbca859f25a9fcf8e018fd1e7e33444ca9ea946ce4b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.11.0/azurefile-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2025-01-06T11:35:23.816493656Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 845a9de8b571b255d05ae9c643d9b90a57fe6507ff3fb735c88b41f99f6f28dc
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.10.0/azurefile-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: v1.9.0
    created: "2025-01-06T11:35:23.8635123Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 59a8057fbbd6d59919b84ef0c3396d5a0a46d1f29df604457db676f4af63c714
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.9.0/azurefile-csi-driver-v1.9.0.tgz
    version: v1.9.0
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2025-01-06T11:35:23.862492286Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 455b7c342194311046df526d10926d94f3bef24f753a07003fb1cad211c4cb52
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.8.0/azurefile-csi-driver-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.7.0
    created: "2025-01-06T11:35:23.861493241Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 057b3f6ef6001d3457fbffc27f90316c981a089696abd3d38bcc8de5537dfa6f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.7.0/azurefile-csi-driver-v1.7.0.tgz
    version: v1.7.0
  - apiVersion: v1
    appVersion: v1.6.0
    created: "2025-01-06T11:35:23.860690982Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: cc2a0dda824cdda4e8141e26878bbb481c5a52e45785a5dbf72e54f2a376e522
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.6.0/azurefile-csi-driver-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2025-01-06T11:35:23.859980923Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2258177477415ddecd83dc46dfd88833223623224c7fe396590b617082bcd845
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.5.0/azurefile-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2025-01-06T11:35:23.859000396Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 40e9bc4ee187789166fcb7c3c82b85b33ecd3a6096266fe74e411d6b48961ece
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.4.0/azurefile-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2025-01-06T11:35:23.857659412Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 12942f422b7cccbfe950bbdbd5c844f5ae4b7c292f32389cba312730a6fe9a62
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.3.0/azurefile-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2025-01-06T11:35:23.827796261Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: b62f44b757416a9e1f5a91e19285f5f5056ec6068802dd9cd82373bef40c9ee9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.2.0/azurefile-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2025-01-06T11:35:23.815496343Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 675d96b309a1c5c491053ebbb854c046737420929c4f0692839afdaaf0db3933
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.1.0/azurefile-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2025-01-06T11:35:23.814982272Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6fd5e54e949ef1061a08d5477bc580204c91dde8f01da195e95dd60ade209492
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.0.0/azurefile-csi-driver-v1.0.0.tgz
    version: v1.0.0
generated: "2025-01-06T11:35:23.813050178Z"
