apiVersion: v1
entries:
  azurefile-csi-driver:
  - apiVersion: v1
    appVersion: v1.26.9
    created: "2023-10-19T03:53:23.594298043Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 0a758e7e5273a7f3561186007e69acf66f2faf0c4b10d264c6ce6720b943545f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/latest/azurefile-csi-driver-v1.26.9.tgz
    version: v1.26.9
  - apiVersion: v1
    appVersion: v1.26.9
    created: "2023-10-19T03:53:23.626952494Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 0a758e7e5273a7f3561186007e69acf66f2faf0c4b10d264c6ce6720b943545f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.9/azurefile-csi-driver-v1.26.9.tgz
    version: v1.26.9
  - apiVersion: v1
    appVersion: v1.26.8
    created: "2023-10-19T03:53:23.625918042Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: be6248e8cc3e5dcefdea746d4b5c288fade8245fbfb9cccbbf79d0fb8d709a1c
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.8/azurefile-csi-driver-v1.26.8.tgz
    version: v1.26.8
  - apiVersion: v1
    appVersion: v1.26.7
    created: "2023-10-19T03:53:23.62403528Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 4b20c18d96005f1146b02078165dc1d2414d47486d28021bbbcd0a224906687a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.7/azurefile-csi-driver-v1.26.7.tgz
    version: v1.26.7
  - apiVersion: v1
    appVersion: v1.26.6
    created: "2023-10-19T03:53:23.62304102Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 3c20488343b47ed618e8c809f6fcdd83f22e00a4d07c78ca097573cafd7075a9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.6/azurefile-csi-driver-v1.26.6.tgz
    version: v1.26.6
  - apiVersion: v1
    appVersion: v1.26.5
    created: "2023-10-19T03:53:23.622042734Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 62ac6ab864264ee1e2fb86e8093c8e8263c2c0d3bafff60704c31fd72e40c604
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.5/azurefile-csi-driver-v1.26.5.tgz
    version: v1.26.5
  - apiVersion: v1
    appVersion: v1.26.4
    created: "2023-10-19T03:53:23.621069514Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 48814d33a7c82ee87d4e153d5c214b446ec7e31c2d368d57919c0f35abecfe1e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.4/azurefile-csi-driver-v1.26.4.tgz
    version: v1.26.4
  - apiVersion: v1
    appVersion: v1.26.3
    created: "2023-10-19T03:53:23.62003709Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 61be13c10618eb0dac60bd27b26a037b5c251fffc945345d03b207a3e091ba76
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.3/azurefile-csi-driver-v1.26.3.tgz
    version: v1.26.3
  - apiVersion: v1
    appVersion: v1.26.2
    created: "2023-10-19T03:53:23.618024774Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d710b8282d9461946d596a8cbe6b91e57950eb6cf793bc180ad897ab5a07596b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.2/azurefile-csi-driver-v1.26.2.tgz
    version: v1.26.2
  - apiVersion: v1
    appVersion: v1.26.1
    created: "2023-10-19T03:53:23.617006752Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: b1c78e2c38869f9430f3e2e671fb168db803eab2fbc0ef905eacdf8794d7968a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.1/azurefile-csi-driver-v1.26.1.tgz
    version: v1.26.1
  - apiVersion: v1
    appVersion: v1.26.0
    created: "2023-10-19T03:53:23.615988375Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 98d15a8ced671a7c3d9aec8ebe00b58abeecb5f65ab966c9c01c4f39121adc0c
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.0/azurefile-csi-driver-v1.26.0.tgz
    version: v1.26.0
  - apiVersion: v1
    appVersion: v1.25.1
    created: "2023-10-19T03:53:23.615001331Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2bf374cc321c5bc8e76e06cd5df85ce7d7d14574397e7e7f7173077393f554c4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.25.1/azurefile-csi-driver-v1.25.1.tgz
    version: v1.25.1
  - apiVersion: v1
    appVersion: v1.25.0
    created: "2023-10-19T03:53:23.613974279Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: ba80dcd23dade4e62b39d3dc638c599e9d5e100009fa14d4164bfc8966fea3dd
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.25.0/azurefile-csi-driver-v1.25.0.tgz
    version: v1.25.0
  - apiVersion: v1
    appVersion: v1.24.0
    created: "2023-10-19T03:53:23.61212691Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 1905eb862745d4a7f57c5de96848cee194adf827086984b75bcaefce5c90142b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.0/azurefile-csi-driver-v1.24.0.tgz
    version: v1.24.0
  - apiVersion: v1
    appVersion: v1.23.0
    created: "2023-10-19T03:53:23.611147528Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5fcb33617d16e90df1e7041b0df02e5bd92595e86381db30d356b0b2e3500bc4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.23.0/azurefile-csi-driver-v1.23.0.tgz
    version: v1.23.0
  - apiVersion: v1
    appVersion: v1.22.0
    created: "2023-10-19T03:53:23.610169861Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 253d87a8b876dbdd55870a7fee88547393179d03f193661125f5a0b63411f922
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.22.0/azurefile-csi-driver-v1.22.0.tgz
    version: v1.22.0
  - apiVersion: v1
    appVersion: v1.21.0
    created: "2023-10-19T03:53:23.609148331Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d45bf3455ebadc9cc5afaf9da66aa1ea1d4b719cfdff5af661f93bb26c01a504
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.21.0/azurefile-csi-driver-v1.21.0.tgz
    version: v1.21.0
  - apiVersion: v1
    appVersion: v1.20.0
    created: "2023-10-19T03:53:23.60813699Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 7cc43d57a79137aea5414fb51a9bbd77bb679b29ee49c06865c1a5b9ba60be99
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.20.0/azurefile-csi-driver-v1.20.0.tgz
    version: v1.20.0
  - apiVersion: v1
    appVersion: v1.19.0
    created: "2023-10-19T03:53:23.606195456Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 18f6efbed424efd661fde43be2e5a48a5012a46a7938c33b36963cbd9875a5af
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.19.0/azurefile-csi-driver-v1.19.0.tgz
    version: v1.19.0
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2023-10-19T03:53:23.604803463Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 696ca23d9ee517f71ef5e852955c8d0f1017c331c025426c6fcbe7a06d006c66
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.18.0/azurefile-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2023-10-19T03:53:23.603891297Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5632f61265a3b78dce3e2b15e07cc9b14a7f54a778878c02ca2d9fe69ca0344e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.17.0/azurefile-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2023-10-19T03:53:23.602957979Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: a7a2d57e8eca7dc06c8b2cffb9bccb857753eb110b8e70760b3e04f4e6a87552
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.16.0/azurefile-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2023-10-19T03:53:23.602059084Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: c1a31dadce233a90c19dce70f6cc92ba2e20bbaa1b1883baea72381d09303118
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.15.0/azurefile-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2023-10-19T03:53:23.601123394Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 0c9ad4afa5ebfdb2851ad93eb16a0382d61448714b7556899360730a2fdf463a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.14.0/azurefile-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2023-10-19T03:53:23.600040204Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 214042b029d858b50a0f8bba33a7aa2b41d1b67bce16f957ca183ae7438dac3f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.13.0/azurefile-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2023-10-19T03:53:23.598130962Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fbd63929671066a26df898d32282a6e79c39499a39c71761c546d069459d847d
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.12.0/azurefile-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2023-10-19T03:53:23.597183771Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 76bd438f8391d08235b09fbca859f25a9fcf8e018fd1e7e33444ca9ea946ce4b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.11.0/azurefile-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2023-10-19T03:53:23.59623389Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 845a9de8b571b255d05ae9c643d9b90a57fe6507ff3fb735c88b41f99f6f28dc
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.10.0/azurefile-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: v1.9.0
    created: "2023-10-19T03:53:23.633191004Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 59a8057fbbd6d59919b84ef0c3396d5a0a46d1f29df604457db676f4af63c714
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.9.0/azurefile-csi-driver-v1.9.0.tgz
    version: v1.9.0
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2023-10-19T03:53:23.632199887Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 455b7c342194311046df526d10926d94f3bef24f753a07003fb1cad211c4cb52
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.8.0/azurefile-csi-driver-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.7.0
    created: "2023-10-19T03:53:23.631203175Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 057b3f6ef6001d3457fbffc27f90316c981a089696abd3d38bcc8de5537dfa6f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.7.0/azurefile-csi-driver-v1.7.0.tgz
    version: v1.7.0
  - apiVersion: v1
    appVersion: v1.6.0
    created: "2023-10-19T03:53:23.629525299Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: cc2a0dda824cdda4e8141e26878bbb481c5a52e45785a5dbf72e54f2a376e522
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.6.0/azurefile-csi-driver-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2023-10-19T03:53:23.628827338Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2258177477415ddecd83dc46dfd88833223623224c7fe396590b617082bcd845
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.5.0/azurefile-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2023-10-19T03:53:23.628142113Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 40e9bc4ee187789166fcb7c3c82b85b33ecd3a6096266fe74e411d6b48961ece
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.4.0/azurefile-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2023-10-19T03:53:23.627504613Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 12942f422b7cccbfe950bbdbd5c844f5ae4b7c292f32389cba312730a6fe9a62
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.3.0/azurefile-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2023-10-19T03:53:23.607097281Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: b62f44b757416a9e1f5a91e19285f5f5056ec6068802dd9cd82373bef40c9ee9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.2.0/azurefile-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2023-10-19T03:53:23.595315375Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 675d96b309a1c5c491053ebbb854c046737420929c4f0692839afdaaf0db3933
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.1.0/azurefile-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2023-10-19T03:53:23.594812742Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6fd5e54e949ef1061a08d5477bc580204c91dde8f01da195e95dd60ade209492
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.0.0/azurefile-csi-driver-v1.0.0.tgz
    version: v1.0.0
generated: "2023-10-19T03:53:23.593108794Z"
