apiVersion: v1
entries:
  azurefile-csi-driver:
  - apiVersion: v1
    appVersion: latest
    created: "2021-06-01T06:12:35.826486573Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 0e565fe721977b81f6122d610bbdbaebe4ae2381d762911578ec755c0f7df5d8
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/latest/azurefile-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2021-06-01T06:12:35.837638743Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 12942f422b7cccbfe950bbdbd5c844f5ae4b7c292f32389cba312730a6fe9a62
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.3.0/azurefile-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2021-06-01T06:12:35.836646137Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: b62f44b757416a9e1f5a91e19285f5f5056ec6068802dd9cd82373bef40c9ee9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.2.0/azurefile-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2021-06-01T06:12:35.835103627Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 675d96b309a1c5c491053ebbb854c046737420929c4f0692839afdaaf0db3933
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.1.0/azurefile-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2021-06-01T06:12:35.833834319Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6fd5e54e949ef1061a08d5477bc580204c91dde8f01da195e95dd60ade209492
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.0.0/azurefile-csi-driver-v1.0.0.tgz
    version: v1.0.0
  - apiVersion: v1
    appVersion: v0.10.0
    created: "2021-06-01T06:12:35.827420179Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 8437b70c263de3ba365d4719f1cdd976e7461d217504b43d136d985b40f2f7ef
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.10.0/azurefile-csi-driver-v0.10.0.tgz
    version: v0.10.0
  - apiVersion: v1
    appVersion: v0.9.0
    created: "2021-06-01T06:12:35.832248209Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: ff42d33b0b98ce138e95028e084ce1fe9cecde82d2b96e22ca4aaf3e6453a15b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.9.0/azurefile-csi-driver-v0.9.0.tgz
    version: v0.9.0
  - apiVersion: v1
    appVersion: v0.8.0
    created: "2021-06-01T06:12:35.831339404Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6811326fbd54832ef441bd54bb5a8bf5b0ca4734da1755c84b51ae713e35fb72
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.8.0/azurefile-csi-driver-v0.8.0.tgz
    version: v0.8.0
  - apiVersion: v1
    appVersion: v0.7.0
    created: "2021-06-01T06:12:35.830470098Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: cc529dd3f6d19acc695f79cb08656ed0d8192f449eb70af3ab94d6b76c28c38d
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.7.0/azurefile-csi-driver-v0.7.0.tgz
    version: v0.7.0
  - apiVersion: v1
    appVersion: v0.6.0
    created: "2021-06-01T06:12:35.829868294Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: eb6bc5333d6ed5788c0aa6d42e14e6228c1bf72c0db44de6f60c746e6f0cd3dd
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.6.0/azurefile-csi-driver-v0.6.0.tgz
    version: v0.6.0
  - apiVersion: v1
    appVersion: v0.5.0
    created: "2021-06-01T06:12:35.829288891Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2d16cae9af5e306e4b3f1cba341532089e9871abe31d9ff20f6751215f908a01
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.5.0/azurefile-csi-driver-v0.5.0.tgz
    version: v0.5.0
  - apiVersion: v1
    appVersion: v0.4.0
    created: "2021-06-01T06:12:35.828747788Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fcc251b21abb2a5aee4df751424b33705850226119c1bfbb0c741d0ce020d1f2
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.4.0/azurefile-csi-driver-v0.4.0.tgz
    version: v0.4.0
  - apiVersion: v1
    appVersion: 0.3.0
    created: "2021-06-01T06:12:35.828207584Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d0fa02e4c7c15f106050c6d795e97b437ec8be359d33130ca02509effc1d7082
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.3.0/azurefile-csi-driver-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v1
    appVersion: 0.2.0
    created: "2021-06-01T06:12:35.827824682Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fde4b97c4a57b1aa6a9345e25c29eccc6b83da7746b465813473a955a4fe9896
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v0.2.0/azurefile-csi-driver-0.2.0.tgz
    version: 0.2.0
generated: "2021-06-01T06:12:35.823506155Z"
