apiVersion: v1
entries:
  azurefile-csi-driver:
  - apiVersion: v1
    appVersion: 1.31.0
    created: "2024-10-14T15:21:42.298970094Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: da5e0d5677abc3e0f334ceaf5674cb82ddf644d126b3fcf6ed0032c85a78921f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.31.0/azurefile-csi-driver-1.31.0.tgz
    version: 1.31.0
  - apiVersion: v1
    appVersion: v1.30.5
    created: "2024-10-14T15:21:42.297200216Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 6b3692dac69d38c069f3ad271d4a72db47e99c78b3881644fe970aa3978a29f3
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.30.5/azurefile-csi-driver-v1.30.5.tgz
    version: v1.30.5
  - apiVersion: v1
    appVersion: v1.30.4
    created: "2024-10-14T15:21:42.296104107Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: cc928f9a3704d37838a04e2691714ad97000b8985db1c02be48e30071a94cd3a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.30.4/azurefile-csi-driver-v1.30.4.tgz
    version: v1.30.4
  - apiVersion: v1
    appVersion: v1.30.2
    created: "2024-10-14T15:21:42.295056466Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fc059dd694e8cb922cf7e4c073fe7c6a0beec54cef22a1e2b089280b3957e0eb
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.30.2/azurefile-csi-driver-v1.30.2.tgz
    version: v1.30.2
  - apiVersion: v1
    appVersion: v1.30.1
    created: "2024-10-14T15:21:42.293994372Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 4311cb88212ad1341e2d4bd470aaab03c8cd8397ad9be20177814d3a69bfdd9b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.30.1/azurefile-csi-driver-v1.30.1.tgz
    version: v1.30.1
  - apiVersion: v1
    appVersion: v1.30.0
    created: "2024-10-14T15:21:42.292872542Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 57e4c1185b8941ff9285588791a5d8897883da7fab69f0dd21fadc97bd7553db
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.30.0/azurefile-csi-driver-v1.30.0.tgz
    version: v1.30.0
  - apiVersion: v1
    appVersion: v1.29.7
    created: "2024-10-14T15:21:42.290769952Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d31aba313d13f53e90ad41ccbc65ff4d95c957dd22672d634a98c2a2998dc5e9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.7/azurefile-csi-driver-v1.29.7.tgz
    version: v1.29.7
  - apiVersion: v1
    appVersion: v1.29.5
    created: "2024-10-14T15:21:42.289700543Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: e243170530c27b63b7091543b94ce197eeebbe9f5b1b1075f64af73cd69a43ce
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.5/azurefile-csi-driver-v1.29.5.tgz
    version: v1.29.5
  - apiVersion: v1
    appVersion: v1.29.4
    created: "2024-10-14T15:21:42.288598092Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 16ff777186fc090d80a73551bbe2690a81c4b37a8a64b53e21e58cb9a2ea4570
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.4/azurefile-csi-driver-v1.29.4.tgz
    version: v1.29.4
  - apiVersion: v1
    appVersion: v1.29.2
    created: "2024-10-14T15:21:42.287547014Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 37d89c48dda1666fa0a73a4b038b0f0da7f291b4b07abac47a6ccecda11464b3
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.2/azurefile-csi-driver-v1.29.2.tgz
    version: v1.29.2
  - apiVersion: v1
    appVersion: v1.29.1
    created: "2024-10-14T15:21:42.286451723Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5f1060cf8d7cd81dcde897f7c0ef83908e49145a2af84a3615c8faf4a1cea007
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.1/azurefile-csi-driver-v1.29.1.tgz
    version: v1.29.1
  - apiVersion: v1
    appVersion: v1.29.0
    created: "2024-10-14T15:21:42.284486792Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2da242b471ff0eaf6ea3f1a9d2c1f6aaa1b78c8cbb4e850bbefb336e043b8098
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.29.0/azurefile-csi-driver-v1.29.0.tgz
    version: v1.29.0
  - apiVersion: v1
    appVersion: v1.28.12
    created: "2024-10-14T15:21:42.27715146Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 68de5f2048c770bff5d95966c1af00375b7bfc0f8b7e114c807b6e8958538a76
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.12/azurefile-csi-driver-v1.28.12.tgz
    version: v1.28.12
  - apiVersion: v1
    appVersion: v1.28.10
    created: "2024-10-14T15:21:42.27608971Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 9c7bae01fc3770550ebddcd5045f69d66baca6c6fc4678da3de6c1d4f63a3592
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.10/azurefile-csi-driver-v1.28.10.tgz
    version: v1.28.10
  - apiVersion: v1
    appVersion: v1.28.9
    created: "2024-10-14T15:21:42.283417535Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 489319dfa4bd9efeefede1fac20bbead9d309da3c90f34d178c30054d562881f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.9/azurefile-csi-driver-v1.28.9.tgz
    version: v1.28.9
  - apiVersion: v1
    appVersion: v1.28.7
    created: "2024-10-14T15:21:42.282339534Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 7bb57767321958e5851b621962988fb7e245f583430cb19a573b28d33f83d923
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.7/azurefile-csi-driver-v1.28.7.tgz
    version: v1.28.7
  - apiVersion: v1
    appVersion: v1.28.6
    created: "2024-10-14T15:21:42.281262366Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: cdf86fd396da34c8bf6c401d236dc12ce24697fa8565c63c605f8b5d8d1b195b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.6/azurefile-csi-driver-v1.28.6.tgz
    version: v1.28.6
  - apiVersion: v1
    appVersion: v1.28.3
    created: "2024-10-14T15:21:42.280122421Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 58e138f7a8f2a925c56ca26dc220cab2dc723691c23fd011b457624d11889395
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.3/azurefile-csi-driver-v1.28.3.tgz
    version: v1.28.3
  - apiVersion: v1
    appVersion: v1.28.2
    created: "2024-10-14T15:21:42.278200689Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 426fad83a42035af15af775bd37c73309ef0cfe22686babb0668be71da70a66e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.28.2/azurefile-csi-driver-v1.28.2.tgz
    version: v1.28.2
  - apiVersion: v1
    appVersion: v1.27.3
    created: "2024-10-14T15:21:42.275009501Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 330d2b11f93e2b10d36f64ed6de528b61351ca794dd9b2c3690c6f6790008732
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.27.3/azurefile-csi-driver-v1.27.3.tgz
    version: v1.27.3
  - apiVersion: v1
    appVersion: v1.27.2
    created: "2024-10-14T15:21:42.273965111Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: ab72e0e5f360a38f63e87147ef47ef213016578e8ba64fbb32ecaf2aad7ffdf3
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.27.2/azurefile-csi-driver-v1.27.2.tgz
    version: v1.27.2
  - apiVersion: v1
    appVersion: v1.26.10
    created: "2024-10-14T15:21:42.269567075Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 80d2fccdab497044587f8a3299cc761cdf364c2d2d0b4f4cb0ab8197021dc218
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.10/azurefile-csi-driver-v1.26.10.tgz
    version: v1.26.10
  - apiVersion: v1
    appVersion: v1.26.6
    created: "2024-10-14T15:21:42.272673029Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 3c20488343b47ed618e8c809f6fcdd83f22e00a4d07c78ca097573cafd7075a9
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.6/azurefile-csi-driver-v1.26.6.tgz
    version: v1.26.6
  - apiVersion: v1
    appVersion: v1.26.5
    created: "2024-10-14T15:21:42.270545872Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 62ac6ab864264ee1e2fb86e8093c8e8263c2c0d3bafff60704c31fd72e40c604
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.26.5/azurefile-csi-driver-v1.26.5.tgz
    version: v1.26.5
  - apiVersion: v1
    appVersion: v1.25.1
    created: "2024-10-14T15:21:42.26853743Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 2bf374cc321c5bc8e76e06cd5df85ce7d7d14574397e7e7f7173077393f554c4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.25.1/azurefile-csi-driver-v1.25.1.tgz
    version: v1.25.1
  - apiVersion: v1
    appVersion: v1.24.11
    created: "2024-10-14T15:21:42.264626095Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 501e27a634966a4ae5528025577e926745d896ffa2c253dc69c13623b84254d2
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.11/azurefile-csi-driver-v1.24.11.tgz
    version: v1.24.11
  - apiVersion: v1
    appVersion: v1.24.7
    created: "2024-10-14T15:21:42.267566359Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 9e5b3f32ad823f845e5a09af230f7a934851943d6afcab3bd545233838680d83
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.7/azurefile-csi-driver-v1.24.7.tgz
    version: v1.24.7
  - apiVersion: v1
    appVersion: v1.24.6
    created: "2024-10-14T15:21:42.266536292Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: dbd0a6e27a09fec002c57029bd6e34a6ee92d1c10e708935e3f2150069a35ee5
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.24.6/azurefile-csi-driver-v1.24.6.tgz
    version: v1.24.6
  - apiVersion: v1
    appVersion: v1.23.0
    created: "2024-10-14T15:21:42.263632567Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5fcb33617d16e90df1e7041b0df02e5bd92595e86381db30d356b0b2e3500bc4
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.23.0/azurefile-csi-driver-v1.23.0.tgz
    version: v1.23.0
  - apiVersion: v1
    appVersion: v1.22.0
    created: "2024-10-14T15:21:42.262625943Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 253d87a8b876dbdd55870a7fee88547393179d03f193661125f5a0b63411f922
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.22.0/azurefile-csi-driver-v1.22.0.tgz
    version: v1.22.0
  - apiVersion: v1
    appVersion: v1.21.0
    created: "2024-10-14T15:21:42.2616399Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: d45bf3455ebadc9cc5afaf9da66aa1ea1d4b719cfdff5af661f93bb26c01a504
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.21.0/azurefile-csi-driver-v1.21.0.tgz
    version: v1.21.0
  - apiVersion: v1
    appVersion: v1.20.0
    created: "2024-10-14T15:21:42.26063253Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 7cc43d57a79137aea5414fb51a9bbd77bb679b29ee49c06865c1a5b9ba60be99
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.20.0/azurefile-csi-driver-v1.20.0.tgz
    version: v1.20.0
  - apiVersion: v1
    appVersion: v1.19.0
    created: "2024-10-14T15:21:42.258652643Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 18f6efbed424efd661fde43be2e5a48a5012a46a7938c33b36963cbd9875a5af
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.19.0/azurefile-csi-driver-v1.19.0.tgz
    version: v1.19.0
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2024-10-14T15:21:42.257737356Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 696ca23d9ee517f71ef5e852955c8d0f1017c331c025426c6fcbe7a06d006c66
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.18.0/azurefile-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2024-10-14T15:21:42.256728031Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 5632f61265a3b78dce3e2b15e07cc9b14a7f54a778878c02ca2d9fe69ca0344e
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.17.0/azurefile-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2024-10-14T15:21:42.255792217Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: a7a2d57e8eca7dc06c8b2cffb9bccb857753eb110b8e70760b3e04f4e6a87552
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.16.0/azurefile-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2024-10-14T15:21:42.25488365Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: c1a31dadce233a90c19dce70f6cc92ba2e20bbaa1b1883baea72381d09303118
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.15.0/azurefile-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2024-10-14T15:21:42.253854329Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 0c9ad4afa5ebfdb2851ad93eb16a0382d61448714b7556899360730a2fdf463a
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.14.0/azurefile-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2024-10-14T15:21:42.252618272Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 214042b029d858b50a0f8bba33a7aa2b41d1b67bce16f957ca183ae7438dac3f
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.13.0/azurefile-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2024-10-14T15:21:42.250937057Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: fbd63929671066a26df898d32282a6e79c39499a39c71761c546d069459d847d
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.12.0/azurefile-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2024-10-14T15:21:42.249997638Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 76bd438f8391d08235b09fbca859f25a9fcf8e018fd1e7e33444ca9ea946ce4b
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.11.0/azurefile-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2024-10-14T15:21:42.248997744Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: 845a9de8b571b255d05ae9c643d9b90a57fe6507ff3fb735c88b41f99f6f28dc
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/v1.10.0/azurefile-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: latest
    created: "2024-10-14T15:21:42.248036219Z"
    description: Azure File Container Storage Interface (CSI) Storage Plugin
    digest: e6da963cf8ffa4f348346af3818d5e40d2814bbf22b01c26a0cda32499227eed
    name: azurefile-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/azurefile-csi-driver/master/charts/latest/azurefile-csi-driver-v0.0.0.tgz
    version: v0.0.0
generated: "2024-10-14T15:21:42.246736788Z"
